/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-08 at 13:14:32 UTC 
 * Modify at your own risk.
 */

package com.jtristan.reservarestaurantev2.entidades.restauranteendpoint;

/**
 * Service definition for Restauranteendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RestauranteendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Restauranteendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the restauranteendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "restauranteendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Restauranteendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Restauranteendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getRestaurante".
   *
   * This request holds the parameters needed by the the restauranteendpoint server.  After setting
   * any optional parameters, call the {@link GetRestaurante#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetRestaurante getRestaurante(java.lang.Long id) throws java.io.IOException {
    GetRestaurante result = new GetRestaurante(id);
    initialize(result);
    return result;
  }

  public class GetRestaurante extends RestauranteendpointRequest<com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante> {

    private static final String REST_PATH = "restaurante/{id}";

    /**
     * Create a request for the method "getRestaurante".
     *
     * This request holds the parameters needed by the the restauranteendpoint server.  After setting
     * any optional parameters, call the {@link GetRestaurante#execute()} method to invoke the remote
     * operation. <p> {@link GetRestaurante#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetRestaurante(java.lang.Long id) {
      super(Restauranteendpoint.this, "GET", REST_PATH, null, com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRestaurante setAlt(java.lang.String alt) {
      return (GetRestaurante) super.setAlt(alt);
    }

    @Override
    public GetRestaurante setFields(java.lang.String fields) {
      return (GetRestaurante) super.setFields(fields);
    }

    @Override
    public GetRestaurante setKey(java.lang.String key) {
      return (GetRestaurante) super.setKey(key);
    }

    @Override
    public GetRestaurante setOauthToken(java.lang.String oauthToken) {
      return (GetRestaurante) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRestaurante setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRestaurante) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRestaurante setQuotaUser(java.lang.String quotaUser) {
      return (GetRestaurante) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRestaurante setUserIp(java.lang.String userIp) {
      return (GetRestaurante) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetRestaurante setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetRestaurante set(String parameterName, Object value) {
      return (GetRestaurante) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRestaurante".
   *
   * This request holds the parameters needed by the the restauranteendpoint server.  After setting
   * any optional parameters, call the {@link InsertRestaurante#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante}
   * @return the request
   */
  public InsertRestaurante insertRestaurante(com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante content) throws java.io.IOException {
    InsertRestaurante result = new InsertRestaurante(content);
    initialize(result);
    return result;
  }

  public class InsertRestaurante extends RestauranteendpointRequest<com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante> {

    private static final String REST_PATH = "restaurante";

    /**
     * Create a request for the method "insertRestaurante".
     *
     * This request holds the parameters needed by the the restauranteendpoint server.  After setting
     * any optional parameters, call the {@link InsertRestaurante#execute()} method to invoke the
     * remote operation. <p> {@link InsertRestaurante#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante}
     * @since 1.13
     */
    protected InsertRestaurante(com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante content) {
      super(Restauranteendpoint.this, "POST", REST_PATH, content, com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante.class);
    }

    @Override
    public InsertRestaurante setAlt(java.lang.String alt) {
      return (InsertRestaurante) super.setAlt(alt);
    }

    @Override
    public InsertRestaurante setFields(java.lang.String fields) {
      return (InsertRestaurante) super.setFields(fields);
    }

    @Override
    public InsertRestaurante setKey(java.lang.String key) {
      return (InsertRestaurante) super.setKey(key);
    }

    @Override
    public InsertRestaurante setOauthToken(java.lang.String oauthToken) {
      return (InsertRestaurante) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRestaurante setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRestaurante) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRestaurante setQuotaUser(java.lang.String quotaUser) {
      return (InsertRestaurante) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRestaurante setUserIp(java.lang.String userIp) {
      return (InsertRestaurante) super.setUserIp(userIp);
    }

    @Override
    public InsertRestaurante set(String parameterName, Object value) {
      return (InsertRestaurante) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRestaurante".
   *
   * This request holds the parameters needed by the the restauranteendpoint server.  After setting
   * any optional parameters, call the {@link ListRestaurante#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListRestaurante listRestaurante() throws java.io.IOException {
    ListRestaurante result = new ListRestaurante();
    initialize(result);
    return result;
  }

  public class ListRestaurante extends RestauranteendpointRequest<com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.CollectionResponseRestaurante> {

    private static final String REST_PATH = "restaurante";

    /**
     * Create a request for the method "listRestaurante".
     *
     * This request holds the parameters needed by the the restauranteendpoint server.  After setting
     * any optional parameters, call the {@link ListRestaurante#execute()} method to invoke the remote
     * operation. <p> {@link ListRestaurante#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListRestaurante() {
      super(Restauranteendpoint.this, "GET", REST_PATH, null, com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.CollectionResponseRestaurante.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRestaurante setAlt(java.lang.String alt) {
      return (ListRestaurante) super.setAlt(alt);
    }

    @Override
    public ListRestaurante setFields(java.lang.String fields) {
      return (ListRestaurante) super.setFields(fields);
    }

    @Override
    public ListRestaurante setKey(java.lang.String key) {
      return (ListRestaurante) super.setKey(key);
    }

    @Override
    public ListRestaurante setOauthToken(java.lang.String oauthToken) {
      return (ListRestaurante) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRestaurante setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRestaurante) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRestaurante setQuotaUser(java.lang.String quotaUser) {
      return (ListRestaurante) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRestaurante setUserIp(java.lang.String userIp) {
      return (ListRestaurante) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListRestaurante setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListRestaurante setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListRestaurante set(String parameterName, Object value) {
      return (ListRestaurante) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRestaurante".
   *
   * This request holds the parameters needed by the the restauranteendpoint server.  After setting
   * any optional parameters, call the {@link RemoveRestaurante#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRestaurante removeRestaurante(java.lang.Long id) throws java.io.IOException {
    RemoveRestaurante result = new RemoveRestaurante(id);
    initialize(result);
    return result;
  }

  public class RemoveRestaurante extends RestauranteendpointRequest<Void> {

    private static final String REST_PATH = "restaurante/{id}";

    /**
     * Create a request for the method "removeRestaurante".
     *
     * This request holds the parameters needed by the the restauranteendpoint server.  After setting
     * any optional parameters, call the {@link RemoveRestaurante#execute()} method to invoke the
     * remote operation. <p> {@link RemoveRestaurante#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRestaurante(java.lang.Long id) {
      super(Restauranteendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRestaurante setAlt(java.lang.String alt) {
      return (RemoveRestaurante) super.setAlt(alt);
    }

    @Override
    public RemoveRestaurante setFields(java.lang.String fields) {
      return (RemoveRestaurante) super.setFields(fields);
    }

    @Override
    public RemoveRestaurante setKey(java.lang.String key) {
      return (RemoveRestaurante) super.setKey(key);
    }

    @Override
    public RemoveRestaurante setOauthToken(java.lang.String oauthToken) {
      return (RemoveRestaurante) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRestaurante setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRestaurante) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRestaurante setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRestaurante) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRestaurante setUserIp(java.lang.String userIp) {
      return (RemoveRestaurante) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveRestaurante setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRestaurante set(String parameterName, Object value) {
      return (RemoveRestaurante) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateRestaurante".
   *
   * This request holds the parameters needed by the the restauranteendpoint server.  After setting
   * any optional parameters, call the {@link UpdateRestaurante#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante}
   * @return the request
   */
  public UpdateRestaurante updateRestaurante(com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante content) throws java.io.IOException {
    UpdateRestaurante result = new UpdateRestaurante(content);
    initialize(result);
    return result;
  }

  public class UpdateRestaurante extends RestauranteendpointRequest<com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante> {

    private static final String REST_PATH = "restaurante";

    /**
     * Create a request for the method "updateRestaurante".
     *
     * This request holds the parameters needed by the the restauranteendpoint server.  After setting
     * any optional parameters, call the {@link UpdateRestaurante#execute()} method to invoke the
     * remote operation. <p> {@link UpdateRestaurante#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante}
     * @since 1.13
     */
    protected UpdateRestaurante(com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante content) {
      super(Restauranteendpoint.this, "PUT", REST_PATH, content, com.jtristan.reservarestaurantev2.entidades.restauranteendpoint.model.Restaurante.class);
    }

    @Override
    public UpdateRestaurante setAlt(java.lang.String alt) {
      return (UpdateRestaurante) super.setAlt(alt);
    }

    @Override
    public UpdateRestaurante setFields(java.lang.String fields) {
      return (UpdateRestaurante) super.setFields(fields);
    }

    @Override
    public UpdateRestaurante setKey(java.lang.String key) {
      return (UpdateRestaurante) super.setKey(key);
    }

    @Override
    public UpdateRestaurante setOauthToken(java.lang.String oauthToken) {
      return (UpdateRestaurante) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateRestaurante setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateRestaurante) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateRestaurante setQuotaUser(java.lang.String quotaUser) {
      return (UpdateRestaurante) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateRestaurante setUserIp(java.lang.String userIp) {
      return (UpdateRestaurante) super.setUserIp(userIp);
    }

    @Override
    public UpdateRestaurante set(String parameterName, Object value) {
      return (UpdateRestaurante) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Restauranteendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Restauranteendpoint}. */
    @Override
    public Restauranteendpoint build() {
      return new Restauranteendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RestauranteendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRestauranteendpointRequestInitializer(
        RestauranteendpointRequestInitializer restauranteendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(restauranteendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
