/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-08 at 13:13:50 UTC 
 * Modify at your own risk.
 */

package com.jtristan.reservarestaurantev2.entidades.cartaendpoint;

/**
 * Service definition for Cartaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CartaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Cartaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the cartaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "cartaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Cartaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Cartaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getCarta".
   *
   * This request holds the parameters needed by the the cartaendpoint server.  After setting any
   * optional parameters, call the {@link GetCarta#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetCarta getCarta(java.lang.Long id) throws java.io.IOException {
    GetCarta result = new GetCarta(id);
    initialize(result);
    return result;
  }

  public class GetCarta extends CartaendpointRequest<com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta> {

    private static final String REST_PATH = "carta/{id}";

    /**
     * Create a request for the method "getCarta".
     *
     * This request holds the parameters needed by the the cartaendpoint server.  After setting any
     * optional parameters, call the {@link GetCarta#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetCarta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetCarta(java.lang.Long id) {
      super(Cartaendpoint.this, "GET", REST_PATH, null, com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCarta setAlt(java.lang.String alt) {
      return (GetCarta) super.setAlt(alt);
    }

    @Override
    public GetCarta setFields(java.lang.String fields) {
      return (GetCarta) super.setFields(fields);
    }

    @Override
    public GetCarta setKey(java.lang.String key) {
      return (GetCarta) super.setKey(key);
    }

    @Override
    public GetCarta setOauthToken(java.lang.String oauthToken) {
      return (GetCarta) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCarta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCarta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCarta setQuotaUser(java.lang.String quotaUser) {
      return (GetCarta) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCarta setUserIp(java.lang.String userIp) {
      return (GetCarta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetCarta setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetCarta set(String parameterName, Object value) {
      return (GetCarta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertCarta".
   *
   * This request holds the parameters needed by the the cartaendpoint server.  After setting any
   * optional parameters, call the {@link InsertCarta#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta}
   * @return the request
   */
  public InsertCarta insertCarta(com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta content) throws java.io.IOException {
    InsertCarta result = new InsertCarta(content);
    initialize(result);
    return result;
  }

  public class InsertCarta extends CartaendpointRequest<com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta> {

    private static final String REST_PATH = "carta";

    /**
     * Create a request for the method "insertCarta".
     *
     * This request holds the parameters needed by the the cartaendpoint server.  After setting any
     * optional parameters, call the {@link InsertCarta#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertCarta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta}
     * @since 1.13
     */
    protected InsertCarta(com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta content) {
      super(Cartaendpoint.this, "POST", REST_PATH, content, com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta.class);
    }

    @Override
    public InsertCarta setAlt(java.lang.String alt) {
      return (InsertCarta) super.setAlt(alt);
    }

    @Override
    public InsertCarta setFields(java.lang.String fields) {
      return (InsertCarta) super.setFields(fields);
    }

    @Override
    public InsertCarta setKey(java.lang.String key) {
      return (InsertCarta) super.setKey(key);
    }

    @Override
    public InsertCarta setOauthToken(java.lang.String oauthToken) {
      return (InsertCarta) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertCarta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertCarta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertCarta setQuotaUser(java.lang.String quotaUser) {
      return (InsertCarta) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertCarta setUserIp(java.lang.String userIp) {
      return (InsertCarta) super.setUserIp(userIp);
    }

    @Override
    public InsertCarta set(String parameterName, Object value) {
      return (InsertCarta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCarta".
   *
   * This request holds the parameters needed by the the cartaendpoint server.  After setting any
   * optional parameters, call the {@link ListCarta#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListCarta listCarta() throws java.io.IOException {
    ListCarta result = new ListCarta();
    initialize(result);
    return result;
  }

  public class ListCarta extends CartaendpointRequest<com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.CollectionResponseCarta> {

    private static final String REST_PATH = "carta";

    /**
     * Create a request for the method "listCarta".
     *
     * This request holds the parameters needed by the the cartaendpoint server.  After setting any
     * optional parameters, call the {@link ListCarta#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListCarta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListCarta() {
      super(Cartaendpoint.this, "GET", REST_PATH, null, com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.CollectionResponseCarta.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCarta setAlt(java.lang.String alt) {
      return (ListCarta) super.setAlt(alt);
    }

    @Override
    public ListCarta setFields(java.lang.String fields) {
      return (ListCarta) super.setFields(fields);
    }

    @Override
    public ListCarta setKey(java.lang.String key) {
      return (ListCarta) super.setKey(key);
    }

    @Override
    public ListCarta setOauthToken(java.lang.String oauthToken) {
      return (ListCarta) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCarta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCarta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCarta setQuotaUser(java.lang.String quotaUser) {
      return (ListCarta) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCarta setUserIp(java.lang.String userIp) {
      return (ListCarta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListCarta setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListCarta setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListCarta set(String parameterName, Object value) {
      return (ListCarta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeCarta".
   *
   * This request holds the parameters needed by the the cartaendpoint server.  After setting any
   * optional parameters, call the {@link RemoveCarta#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveCarta removeCarta(java.lang.Long id) throws java.io.IOException {
    RemoveCarta result = new RemoveCarta(id);
    initialize(result);
    return result;
  }

  public class RemoveCarta extends CartaendpointRequest<Void> {

    private static final String REST_PATH = "carta/{id}";

    /**
     * Create a request for the method "removeCarta".
     *
     * This request holds the parameters needed by the the cartaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveCarta#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveCarta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveCarta(java.lang.Long id) {
      super(Cartaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveCarta setAlt(java.lang.String alt) {
      return (RemoveCarta) super.setAlt(alt);
    }

    @Override
    public RemoveCarta setFields(java.lang.String fields) {
      return (RemoveCarta) super.setFields(fields);
    }

    @Override
    public RemoveCarta setKey(java.lang.String key) {
      return (RemoveCarta) super.setKey(key);
    }

    @Override
    public RemoveCarta setOauthToken(java.lang.String oauthToken) {
      return (RemoveCarta) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveCarta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveCarta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveCarta setQuotaUser(java.lang.String quotaUser) {
      return (RemoveCarta) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveCarta setUserIp(java.lang.String userIp) {
      return (RemoveCarta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveCarta setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveCarta set(String parameterName, Object value) {
      return (RemoveCarta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateCarta".
   *
   * This request holds the parameters needed by the the cartaendpoint server.  After setting any
   * optional parameters, call the {@link UpdateCarta#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta}
   * @return the request
   */
  public UpdateCarta updateCarta(com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta content) throws java.io.IOException {
    UpdateCarta result = new UpdateCarta(content);
    initialize(result);
    return result;
  }

  public class UpdateCarta extends CartaendpointRequest<com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta> {

    private static final String REST_PATH = "carta";

    /**
     * Create a request for the method "updateCarta".
     *
     * This request holds the parameters needed by the the cartaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateCarta#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateCarta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta}
     * @since 1.13
     */
    protected UpdateCarta(com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta content) {
      super(Cartaendpoint.this, "PUT", REST_PATH, content, com.jtristan.reservarestaurantev2.entidades.cartaendpoint.model.Carta.class);
    }

    @Override
    public UpdateCarta setAlt(java.lang.String alt) {
      return (UpdateCarta) super.setAlt(alt);
    }

    @Override
    public UpdateCarta setFields(java.lang.String fields) {
      return (UpdateCarta) super.setFields(fields);
    }

    @Override
    public UpdateCarta setKey(java.lang.String key) {
      return (UpdateCarta) super.setKey(key);
    }

    @Override
    public UpdateCarta setOauthToken(java.lang.String oauthToken) {
      return (UpdateCarta) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateCarta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateCarta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateCarta setQuotaUser(java.lang.String quotaUser) {
      return (UpdateCarta) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateCarta setUserIp(java.lang.String userIp) {
      return (UpdateCarta) super.setUserIp(userIp);
    }

    @Override
    public UpdateCarta set(String parameterName, Object value) {
      return (UpdateCarta) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Cartaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Cartaendpoint}. */
    @Override
    public Cartaendpoint build() {
      return new Cartaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CartaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCartaendpointRequestInitializer(
        CartaendpointRequestInitializer cartaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(cartaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
