/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-08 at 13:14:45 UTC 
 * Modify at your own risk.
 */

package com.jtristan.reservarestaurantev2.entidades.reservaendpoint.model;

/**
 * Model definition for Reserva.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the reservaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Reserva extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Carta> carta;

  static {
    // hack to force ProGuard to consider Carta used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Carta.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String direccionCalle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer direccionNumero;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String direccionTipo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String estrellas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime horaReserva;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mailUsuario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> nombreComensales;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombreUsuario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numeroPersonas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Oferta> oferta;

  static {
    // hack to force ProGuard to consider Oferta used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Oferta.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Carta> getCarta() {
    return carta;
  }

  /**
   * @param carta carta or {@code null} for none
   */
  public Reserva setCarta(java.util.List<Carta> carta) {
    this.carta = carta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDireccionCalle() {
    return direccionCalle;
  }

  /**
   * @param direccionCalle direccionCalle or {@code null} for none
   */
  public Reserva setDireccionCalle(java.lang.String direccionCalle) {
    this.direccionCalle = direccionCalle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDireccionNumero() {
    return direccionNumero;
  }

  /**
   * @param direccionNumero direccionNumero or {@code null} for none
   */
  public Reserva setDireccionNumero(java.lang.Integer direccionNumero) {
    this.direccionNumero = direccionNumero;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDireccionTipo() {
    return direccionTipo;
  }

  /**
   * @param direccionTipo direccionTipo or {@code null} for none
   */
  public Reserva setDireccionTipo(java.lang.String direccionTipo) {
    this.direccionTipo = direccionTipo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEstrellas() {
    return estrellas;
  }

  /**
   * @param estrellas estrellas or {@code null} for none
   */
  public Reserva setEstrellas(java.lang.String estrellas) {
    this.estrellas = estrellas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getHoraReserva() {
    return horaReserva;
  }

  /**
   * @param horaReserva horaReserva or {@code null} for none
   */
  public Reserva setHoraReserva(com.google.api.client.util.DateTime horaReserva) {
    this.horaReserva = horaReserva;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Reserva setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMailUsuario() {
    return mailUsuario;
  }

  /**
   * @param mailUsuario mailUsuario or {@code null} for none
   */
  public Reserva setMailUsuario(java.lang.String mailUsuario) {
    this.mailUsuario = mailUsuario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Reserva setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getNombreComensales() {
    return nombreComensales;
  }

  /**
   * @param nombreComensales nombreComensales or {@code null} for none
   */
  public Reserva setNombreComensales(java.util.List<java.lang.String> nombreComensales) {
    this.nombreComensales = nombreComensales;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombreUsuario() {
    return nombreUsuario;
  }

  /**
   * @param nombreUsuario nombreUsuario or {@code null} for none
   */
  public Reserva setNombreUsuario(java.lang.String nombreUsuario) {
    this.nombreUsuario = nombreUsuario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumeroPersonas() {
    return numeroPersonas;
  }

  /**
   * @param numeroPersonas numeroPersonas or {@code null} for none
   */
  public Reserva setNumeroPersonas(java.lang.Integer numeroPersonas) {
    this.numeroPersonas = numeroPersonas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Oferta> getOferta() {
    return oferta;
  }

  /**
   * @param oferta oferta or {@code null} for none
   */
  public Reserva setOferta(java.util.List<Oferta> oferta) {
    this.oferta = oferta;
    return this;
  }

  @Override
  public Reserva set(String fieldName, Object value) {
    return (Reserva) super.set(fieldName, value);
  }

  @Override
  public Reserva clone() {
    return (Reserva) super.clone();
  }

}
